version: '2'

services:
  dockerapp:
    extends:
      file: docker-compose-common.yml
      service: dockerapp
    build: Dockerfile.local
    volumes:
     - ./app:/app

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis