version: '2'

services:
  dockerapp:
    extends:
      file: docker-compose-common.yml
      service: dockerapp
    image: froa/dockerapp

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis
