version: '2'

services:
  dockerapp:
    extends:
      file: docker-compose-common.yml
      service: dockerapp
    image: froa/dockerapp
    # siempre el container dockerapp correra sobre el nodo master.
    environment: 
      - constraint:node==master
    depends_on:
      - redis
    networks:
      - mynet

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis
    networks:
      - mynet

networks:
  mynet:
    driver: overlay